spring:
  profiles: production
server:
  port: 8443
  ssl:
      key-store: classpath:shashafushi.cn.jks
      key-store-password: l47f38d011
      key-store-type: JKS
      key-alias: shashafushi.cn
      protocol: TLS
      enabled: true
tomcat:
   protocol-header-https-value: https
---
spring:
  profiles: test
server:
  port: 80

---
spring:
    profiles:
        active: production
    datasource:
        url: jdbc:mysql://134.175.241.129:3306/uniforms_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    jackson:
        serialization:
          INDENT_OUTPUT: true
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: rppt
        jedis:
          pool:
              max-idle: 8
              min-idle: 0
              max-active: 8
              max-wait: 5000s
        timeout: 5000s


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yidong.model

debug: false
